// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Form(Props) {
  var onSubmit = Props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var value = match[0];
  var handleInput = function (evt) {
    var target = evt.target;
    return Curry._1(setValue, target.value);
  };
  var handleSubmit = function (evt) {
    evt.preventDefault();
    Curry._1(onSubmit, value);
    return Curry._1(setValue, (function (param) {
                  return "";
                }));
  };
  return React.createElement("form", {
              onSubmit: handleSubmit
            }, React.createElement("input", {
                  autoFocus: true,
                  value: value,
                  onInput: handleInput
                }), React.createElement("button", {
                  type: "submit"
                }, "Submit"));
}

var make = Form;

export {
  make ,
  
}
/* react Not a pure module */
